### ISSUE TITLE
clicking on photo with removed background doesnot open the real link

### ISSUE THREAD

**Issue by prabhavagrawal7** [DeepranjanG/Image_Background_Removal#2]
You just need to change 
**from** 
          `  <a href="/static/uploads/detected.jpg" target="_new"><img src="/static/uploads/detected.png" class="upload-image-thumb"></a>`

**to**
           ` <a href="/static/uploads/detected.png" target="_new"><img src="/static/uploads/detected.png" class="upload-image-thumb"></a>`

in line no 23 of uploaded.html

Btw, great job brother for giving such a beautiful project.

**Comment by DeepranjanG** [comment]
Glad you like it and thanks for the solution!!!
